german_words = {
    'der Abschluss': {'meanings': ['graduation', 'completion', 'conclusion', 'qualification']},
    'die Abteilung': {'meanings': ['department', 'division', 'section', 'unit']},
    'der Alltag': {'meanings': ['everyday life', 'daily routine', 'day-to-day life', 'routine']},
    'das Alter': {'meanings': ['age', 'old age', 'years', 'lifetime']},
    'die Analyse': {'meanings': ['analysis', 'examination', 'evaluation', 'assessment']},
    'der Anfang': {'meanings': ['beginning', 'start', 'opening', 'onset']},
    'die Angabe': {'meanings': ['information', 'detail', 'statement', 'specification']},
    'die Ankunft': {'meanings': ['arrival', 'coming', 'arrival time', 'reaching']},
    'der Antrag': {'meanings': ['application', 'request', 'petition', 'proposal']},
    'die Antwort': {'meanings': ['answer', 'reply', 'response', 'reaction']},
    'die Arbeit': {'meanings': ['work', 'job', 'labor', 'task']},
    'der Arbeitgeber': {'meanings': ['employer', 'boss', 'company', 'owner']},
    'der Arbeitnehmer': {'meanings': ['employee', 'worker', 'staff member', 'personnel']},
    'der Auftrag': {'meanings': ['order', 'assignment', 'task', 'commission']},
    'der Ausdruck': {'meanings': ['expression', 'term', 'printout', 'phrase']},
    'die Aussage': {'meanings': ['statement', 'claim', 'remark', 'assertion']},
    'die Auswahl': {'meanings': ['selection', 'choice', 'range', 'assortment']},
    'die Auswirkung': {'meanings': ['effect', 'impact', 'consequence', 'influence']},
    'die Aussicht': {'meanings': ['view', 'prospect', 'outlook', 'chance']},
    'der Austausch': {'meanings': ['exchange', 'swap', 'interaction', 'sharing']},
    'beachten': {'meanings': ['observe', 'pay attention to', 'notice', 'comply with']},
    'bedienen': {'meanings': ['operate', 'serve', 'use', 'attend']},
    'befragen': {'meanings': ['question', 'interview', 'ask', 'survey']},
    'beginnen': {'meanings': ['begin', 'start', 'commence', 'initiate']},
    'begründen': {'meanings': ['justify', 'give reasons', 'explain', 'establish']},
    'beitragen': {'meanings': ['contribute', 'help', 'add', 'play a part']},
    'bekämpfen': {'meanings': ['fight', 'combat', 'oppose', 'counter']},
    'belasten': {'meanings': ['burden', 'strain', 'stress', 'load']},
    'benutzen': {'meanings': ['use', 'utilize', 'employ', 'make use of']},
    'beraten': {'meanings': ['advise', 'consult', 'counsel', 'recommend']},
    'berechnen': {'meanings': ['calculate', 'compute', 'estimate', 'work out']},
    'bereiten': {'meanings': ['prepare', 'cause', 'make ready', 'arrange']},
    'beruhigen': {'meanings': ['calm', 'reassure', 'soothe', 'relax']},
    'beschäftigen': {'meanings': ['employ', 'occupy', 'deal with', 'engage']},
    'beschließen': {'meanings': ['decide', 'resolve', 'approve', 'determine']},
    'beschützen': {'meanings': ['protect', 'guard', 'defend', 'shield']},
    'besorgen': {'meanings': ['obtain', 'get', 'take care of', 'purchase']},
    'bestellen': {'meanings': ['order', 'request', 'reserve', 'book']},
    'bestrafen': {'meanings': ['punish', 'penalize', 'discipline', 'sanction']},
    'besuchen': {'meanings': ['visit', 'attend', 'call on', 'go to']},
    'bezahlen': {'meanings': ['pay', 'settle', 'cover', 'finance']},
    'danken': {'meanings': ['thank', 'express gratitude', 'appreciate', 'be grateful']},
    'darstellen': {'meanings': ['present', 'depict', 'represent', 'illustrate']},
    'denken': {'meanings': ['think', 'consider', 'believe', 'reflect']},
    'drücken': {'meanings': ['press', 'push', 'squeeze', 'express']},
    'drohen': {'meanings': ['threaten', 'warn', 'loom', 'endanger']},
    'einladen': {'meanings': ['invite', 'ask over', 'welcome', 'request presence']},
    'einreichen': {'meanings': ['submit', 'hand in', 'file', 'present']},
    'empfinden': {'meanings': ['feel', 'perceive', 'sense', 'experience']},
    'entfernen': {'meanings': ['remove', 'take away', 'eliminate', 'distance']},
    'entschuldigen': {'meanings': ['apologize', 'excuse', 'forgive', 'pardon']},
    'erfinden': {'meanings': ['invent', 'create', 'devise', 'make up']},
    'erfolgen': {'meanings': ['occur', 'take place', 'happen', 'follow']},
    'erinnern': {'meanings': ['remember', 'remind', 'recall', 'bring to mind']},
    'erlaubnis': {'meanings': ['permission', 'approval', 'consent', 'authorization']},
    'erzählen': {'meanings': ['tell', 'narrate', 'relate', 'recount']},
    'fehlen': {'meanings': ['be missing', 'lack', 'be absent', 'miss']},
    'feiern': {'meanings': ['celebrate', 'party', 'observe', 'commemorate']},
    'finden': {'meanings': ['find', 'discover', 'locate', 'consider']},
    'folgen': {'meanings': ['follow', 'come after', 'obey', 'result']},
    'fordern': {'meanings': ['demand', 'require', 'claim', 'request']},
    'fragen': {'meanings': ['ask', 'question', 'inquire', 'query']},
    'führen': {'meanings': ['lead', 'guide', 'conduct', 'manage']},
    'füllen': {'meanings': ['fill', 'populate', 'complete', 'occupy']},
    'gefallen': {'meanings': ['please', 'appeal', 'be pleasing', 'like']},
    'gelangen': {'meanings': ['reach', 'arrive', 'get to', 'attain']},
    'genügen': {'meanings': ['be enough', 'suffice', 'satisfy', 'meet requirements']},
    'geschehen': {'meanings': ['happen', 'occur', 'take place', 'transpire']},
    'gewinnen': {'meanings': ['win', 'gain', 'earn', 'acquire']},
    'glauben': {'meanings': ['believe', 'think', 'trust', 'suppose']},
    'gratulieren': {'meanings': ['congratulate', 'praise', 'compliment', 'commend']},
    'helfen': {'meanings': ['help', 'assist', 'aid', 'support']},
    'herstellen': {'meanings': ['produce', 'manufacture', 'make', 'create']},
    'hinweisen': {'meanings': ['point out', 'indicate', 'refer', 'draw attention']},
    'holen': {'meanings': ['fetch', 'get', 'bring', 'pick up']},
    'kaufen': {'meanings': ['buy', 'purchase', 'acquire', 'shop for']},
    'kennen': {'meanings': ['know', 'be familiar with', 'recognize', 'understand']},
    'klären': {'meanings': ['clarify', 'clear up', 'resolve', 'explain']},
    'kochen': {'meanings': ['cook', 'boil', 'prepare food', 'make']},
    'lachen': {'meanings': ['laugh', 'giggle', 'smile', 'chuckle']},
    'landen': {'meanings': ['land', 'arrive', 'touch down', 'come down']},
    'lernen': {'meanings': ['learn', 'study', 'acquire', 'master']},
    'liefern': {'meanings': ['deliver', 'supply', 'provide', 'ship']},
    'lösen': {'meanings': ['solve', 'resolve', 'undo', 'release']},
    'melden': {'meanings': ['report', 'register', 'announce', 'notify']},
    'messen': {'meanings': ['measure', 'assess', 'gauge', 'size']},
    'mieten': {'meanings': ['rent', 'hire', 'lease', 'book']},
    'öffnen': {'meanings': ['open', 'unlock', 'uncover', 'start']},
    'ordnen': {'meanings': ['organize', 'arrange', 'sort', 'classify']},
    'planen': {'meanings': ['plan', 'intend', 'design', 'schedule']},
    'prüfen': {'meanings': ['check', 'inspect', 'test', 'verify']},
    'reisen': {'meanings': ['travel', 'journey', 'tour', 'go']},
    'retten': {'meanings': ['save', 'rescue', 'recover', 'protect']},
    'schicken': {'meanings': ['send', 'dispatch', 'mail', 'forward']},
    'schließen': {'meanings': ['close', 'shut', 'lock', 'conclude']},
    'schreiben': {'meanings': ['write', 'compose', 'record', 'note']},
    'sehen': {'meanings': ['see', 'look', 'watch', 'observe']},
    'senden': {'meanings': ['send', 'transmit', 'forward', 'broadcast']},
    'setzen': {'meanings': ['set', 'place', 'put', 'position']},
    'steigen': {'meanings': ['climb', 'rise', 'increase', 'go up']},
    'stellen': {'meanings': ['place', 'put', 'set', 'position']},
    'suchen': {'meanings': ['search', 'look for', 'seek', 'find']},
    'teilen': {'meanings': ['share', 'divide', 'split', 'distribute']},
    'verbessern': {'meanings': ['improve', 'enhance', 'upgrade', 'refine']},
    'vergleichen': {'meanings': ['compare', 'contrast', 'match', 'measure']},
    'der Vorteil': {'meanings': ['advantage', 'benefit', 'strength', 'asset']},
    'der Nachteil': {'meanings': ['disadvantage', 'drawback', 'weakness', 'downside']},
    'die Voraussetzung': {'meanings': ['requirement', 'prerequisite', 'condition', 'qualification']},
    'die Teilnahme': {'meanings': ['participation', 'attendance', 'involvement', 'engagement']},
    'die Untersuchung': {'meanings': ['investigation', 'examination', 'study', 'inspection']},
    'die Verbindung': {'meanings': ['connection', 'link', 'association', 'contact']},
    'die Verbesserung': {'meanings': ['improvement', 'enhancement', 'progress', 'upgrade']},
    'die Versicherung': {'meanings': ['insurance', 'assurance', 'coverage', 'guarantee']},
    'die Vorstellung': {'meanings': ['presentation', 'introduction', 'idea', 'imagination']},
    'die Vorbereitung': {'meanings': ['preparation', 'planning', 'readiness', 'arrangement']},
    'das Verhalten': {'meanings': ['behavior', 'conduct', 'attitude', 'manner']},
    'das Verhältnis': {'meanings': ['relationship', 'proportion', 'connection', 'ratio']},
    'das Vertrauen': {'meanings': ['trust', 'confidence', 'faith', 'reliance']},
    'das Wachstum': {'meanings': ['growth', 'increase', 'expansion', 'development']},
    'das Werkzeug': {'meanings': ['tool', 'instrument', 'equipment', 'implement']},
    'das Wissen': {'meanings': ['knowledge', 'understanding', 'awareness', 'learning']},
    'abholen': {'meanings': ['pick up', 'collect', 'fetch', 'retrieve']},
    'ablegen': {'meanings': ['take off', 'put down', 'complete', 'deposit']},
    'abschaffen': {'meanings': ['abolish', 'eliminate', 'remove', 'end']},
    'abstimmen': {'meanings': ['vote', 'coordinate', 'adjust', 'agree']},
    'anerkennen': {'meanings': ['recognize', 'acknowledge', 'accept', 'appreciate']},
    'ankommen': {'meanings': ['arrive', 'reach', 'come', 'turn up']},
    'anrufen': {'meanings': ['call', 'telephone', 'ring', 'contact']},
    'anzeigen': {'meanings': ['show', 'display', 'report', 'indicate']},
    'aufbauen': {'meanings': ['build', 'establish', 'construct', 'develop']},
    'aufheben': {'meanings': ['pick up', 'cancel', 'keep', 'lift']},
    'aufpassen': {'meanings': ['pay attention', 'watch out', 'take care', 'be careful']},
    'ausgeben': {'meanings': ['spend', 'issue', 'publish', 'hand out']},
    'ausreichen': {'meanings': ['be enough', 'suffice', 'be sufficient', 'meet']},
    'ausschließen': {'meanings': ['exclude', 'rule out', 'eliminate', 'omit']},
    'ausziehen': {'meanings': ['move out', 'take off', 'remove', 'undress']},
    'beantworten': {'meanings': ['answer', 'reply', 'respond', 'address']},
    'beeilen': {'meanings': ['hurry', 'rush', 'make haste', 'speed up']},
    'befinden': {'meanings': ['find oneself', 'be located', 'feel', 'be']},
    'behalten': {'meanings': ['keep', 'retain', 'hold', 'remember']},
    'bekanntgeben': {'meanings': ['announce', 'publish', 'declare', 'notify']},
    'bemühen': {'meanings': ['make an effort', 'strive', 'endeavor', 'try']},
    'benennen': {'meanings': ['name', 'appoint', 'identify', 'designate']},
    'beruhen': {'meanings': ['be based on', 'rest on', 'depend on', 'derive from']},
    'besorgen': {'meanings': ['obtain', 'purchase', 'get', 'take care of']},
    'bestreiten': {'meanings': ['deny', 'contest', 'cover', 'manage']},
    'bewerben': {'meanings': ['apply', 'advertise', 'promote', 'market']},
    'bezahlen': {'meanings': ['pay', 'settle', 'finance', 'cover']},
    'dauern': {'meanings': ['last', 'continue', 'take', 'endure']},
    'drehen': {'meanings': ['turn', 'rotate', 'spin', 'twist']},
    'einführen': {'meanings': ['introduce', 'implement', 'bring in', 'launch']},
    'einsetzen': {'meanings': ['use', 'deploy', 'insert', 'employ']},
    'empfangen': {'meanings': ['receive', 'welcome', 'pick up', 'accept']},
    'entlassen': {'meanings': ['dismiss', 'release', 'discharge', 'fire']},
    'entsprechen': {'meanings': ['correspond', 'match', 'comply', 'meet']},
    'erfinden': {'meanings': ['invent', 'create', 'devise', 'conceive']},
    'erhöhen': {'meanings': ['increase', 'raise', 'boost', 'elevate']},
    'erledigen': {'meanings': ['complete', 'finish', 'deal with', 'settle']},
    'erscheinen': {'meanings': ['appear', 'be published', 'show up', 'emerge']},
    'erzielen': {'meanings': ['achieve', 'obtain', 'attain', 'gain']},
    'festlegen': {'meanings': ['determine', 'define', 'set', 'specify']},
    'fortsetzen': {'meanings': ['continue', 'resume', 'carry on', 'proceed']},
    'genehmigen': {'meanings': ['approve', 'authorize', 'permit', 'accept']},
    'gestatten': {'meanings': ['allow', 'permit', 'authorize', 'let']},
    'hinzufügen': {'meanings': ['add', 'include', 'append', 'attach']},
    'kümmern': {'meanings': ['care', 'look after', 'concern', 'attend']},
    'kündigen': {'meanings': ['terminate', 'resign', 'cancel', 'give notice']},
    'leisten': {'meanings': ['perform', 'provide', 'accomplish', 'achieve']},
    'nachweisen': {'meanings': ['prove', 'demonstrate', 'verify', 'show']},
    'nennen': {'meanings': ['name', 'call', 'mention', 'state']},
    'nutzen': {'meanings': ['use', 'utilize', 'benefit', 'employ']},
    'organisieren': {'meanings': ['organize', 'arrange', 'coordinate', 'plan']},
    'passen': {'meanings': ['fit', 'match', 'suit', 'be suitable']},
    'pflegen': {'meanings': ['care', 'maintain', 'cultivate', 'look after']},
    'rechnen': {'meanings': ['calculate', 'expect', 'count', 'compute']},
    'reichen': {'meanings': ['hand', 'reach', 'be enough', 'pass']},
    'schaden': {'meanings': ['harm', 'damage', 'injure', 'hurt']},
    'scheinen': {'meanings': ['seem', 'appear', 'shine', 'look']},
    'schützen': {'meanings': ['protect', 'defend', 'guard', 'shield']},
    'sinken': {'meanings': ['sink', 'drop', 'decline', 'fall']},
    'sparen': {'meanings': ['save', 'economize', 'store', 'preserve']},
    'steuern': {'meanings': ['control', 'steer', 'manage', 'direct']},
    'teilen': {'meanings': ['share', 'divide', 'split', 'distribute']},
    'überlegen': {'meanings': ['consider', 'think about', 'reflect', 'ponder']},
    'überweisen': {'meanings': ['transfer', 'remit', 'send', 'wire']},
    'umwandeln': {'meanings': ['convert', 'transform', 'change', 'turn into']},
    'unterhalten': {'meanings': ['entertain', 'maintain', 'converse', 'support']},
    'untersuchen': {'meanings': ['examine', 'investigate', 'inspect', 'analyze']},
    'verändern': {'meanings': ['change', 'alter', 'modify', 'transform']},
    'verbrauchen': {'meanings': ['consume', 'use up', 'spend', 'exhaust']},
    'vereinbaren': {'meanings': ['agree', 'arrange', 'schedule', 'settle']},
    'verfügen': {'meanings': ['dispose of', "have at one's disposal", 'order', 'decree']},
    'vergrößern': {'meanings': ['enlarge', 'increase', 'expand', 'extend']},
    'verkaufen': {'meanings': ['sell', 'market', 'trade', 'retail']},
    'verkleinern': {'meanings': ['reduce', 'shrink', 'decrease', 'minimize']},
    'verlängern': {'meanings': ['extend', 'lengthen', 'renew', 'prolong']},
    'vermieten': {'meanings': ['rent out', 'lease', 'let', 'hire out']},
    'veröffentlichen': {'meanings': ['publish', 'release', 'issue', 'announce']},
    'verschieben': {'meanings': ['postpone', 'move', 'shift', 'delay']},
    'versichern': {'meanings': ['insure', 'assure', 'guarantee', 'confirm']},
    'versorgen': {'meanings': ['supply', 'provide', 'take care of', 'serve']},
    'vorhaben': {'meanings': ['intend', 'plan', 'aim', 'mean']},
    'vorziehen': {'meanings': ['prefer', 'favor', 'choose', 'select']},
    'wiederholen': {'meanings': ['repeat', 'revise', 'rehearse', 'review']},
    'zunehmen': {'meanings': ['increase', 'gain', 'grow', 'rise']},
    'zurückkehren': {'meanings': ['return', 'come back', 'go back', 'revisit']},
    'zusagen': {'meanings': ['agree', 'accept', 'confirm', 'promise']},
    'der Anteil': {'meanings': ['share', 'portion', 'part', 'percentage']},
    'der Anspruch': {'meanings': ['claim', 'expectation', 'entitlement', 'requirement']},
    'der Aufwand': {'meanings': ['effort', 'expense', 'cost', 'workload']},
    'der Beweis': {'meanings': ['proof', 'evidence', 'demonstration', 'verification']},
    'der Beruf': {'meanings': ['profession', 'occupation', 'career', 'job']},
    'der Betrieb': {'meanings': ['business', 'operation', 'company', 'plant']},
    'der Einfluss': {'meanings': ['influence', 'impact', 'effect', 'authority']},
    'der Erfolg': {'meanings': ['success', 'achievement', 'result', 'accomplishment']},
    'der Fortschritt': {'meanings': ['progress', 'advance', 'development', 'improvement']},
    'der Gegenstand': {'meanings': ['object', 'item', 'subject', 'article']},
    'der Grund': {'meanings': ['reason', 'cause', 'basis', 'ground']},
    'der Hinweis': {'meanings': ['hint', 'indication', 'note', 'reference']},
    'der Inhalt': {'meanings': ['content', 'contents', 'substance', 'material']},
    'der Kunde': {'meanings': ['customer', 'client', 'buyer', 'consumer']},
    'der Leiter': {'meanings': ['manager', 'leader', 'head', 'director']},
    'der Ort': {'meanings': ['place', 'location', 'site', 'spot']},
    'der Plan': {'meanings': ['plan', 'scheme', 'strategy', 'design']},
    'der Zweck': {'meanings': ['purpose', 'aim', 'objective', 'goal']},
    'die Absprache': {'meanings': ['agreement', 'arrangement', 'understanding', 'deal']},
    'die Anforderung': {'meanings': ['requirement', 'demand', 'expectation', 'specification']},
    'die Anzeige': {'meanings': ['advertisement', 'notice', 'display', 'report']},
    'die Ausbildungsmöglichkeit': {'meanings': ['training opportunity', 'educational opportunity', 'learning option', 'course opportunity']},
    'die Belastung': {'meanings': ['burden', 'strain', 'stress', 'load']},
    'die Beratung': {'meanings': ['consultation', 'advice', 'guidance', 'counseling']},
    'die Beschreibung': {'meanings': ['description', 'account', 'explanation', 'portrayal']},
    'die Bewegung': {'meanings': ['movement', 'motion', 'exercise', 'shift']},
    'die Chance': {'meanings': ['chance', 'opportunity', 'possibility', 'prospect']},
    'die Diskussion': {'meanings': ['discussion', 'debate', 'conversation', 'argument']},
    'die Energie': {'meanings': ['energy', 'power', 'strength', 'force']},
    'die Forschungseinrichtung': {'meanings': ['research institute', 'research facility', 'laboratory', 'institution']},
    'die Freiheit': {'meanings': ['freedom', 'liberty', 'independence', 'autonomy']},
    'die Gefahr': {'meanings': ['danger', 'risk', 'hazard', 'threat']},
    'die Gemeinschaft': {'meanings': ['community', 'society', 'group', 'association']},
    'die Grenze': {'meanings': ['border', 'boundary', 'limit', 'frontier']},
    'die Hilfe': {'meanings': ['help', 'assistance', 'aid', 'support']},
    'die Information': {'meanings': ['information', 'details', 'data', 'facts']},
    'die Investition': {'meanings': ['investment', 'funding', 'capital', 'expenditure']},
    'die Kraft': {'meanings': ['strength', 'power', 'force', 'energy']},
    'die Krise': {'meanings': ['crisis', 'emergency', 'difficulty', 'hardship']},
    'die Nachfrage': {'meanings': ['demand', 'inquiry', 'request', 'interest']},
    'die Regel': {'meanings': ['rule', 'regulation', 'principle', 'standard']},
    'die Reise': {'meanings': ['journey', 'trip', 'travel', 'tour']},
    'die Schwierigkeit': {'meanings': ['difficulty', 'problem', 'challenge', 'obstacle']},
    'die Suche': {'meanings': ['search', 'quest', 'lookup', 'hunt']},
    'die Technik': {'meanings': ['technology', 'technique', 'method', 'engineering']},
    'die Tradition': {'meanings': ['tradition', 'custom', 'practice', 'heritage']},
    'die Übersetzung': {'meanings': ['translation', 'interpretation', 'rendering', 'version']},
    'die Universität': {'meanings': ['university', 'college', 'institution', 'campus']},
    'die Verwendung': {'meanings': ['use', 'usage', 'application', 'utilization']},
    'die Vision': {'meanings': ['vision', 'idea', 'concept', 'dream']},
    'das Beispiel': {'meanings': ['example', 'instance', 'sample', 'case']},
    'das Gesetz': {'meanings': ['law', 'act', 'regulation', 'rule']},
    'das Gespräch': {'meanings': ['conversation', 'discussion', 'talk', 'dialogue']},
    'das Projekt': {'meanings': ['project', 'assignment', 'plan', 'undertaking']},
    'das Risiko': {'meanings': ['risk', 'danger', 'hazard', 'uncertainty']},
    'das System': {'meanings': ['system', 'framework', 'structure', 'network']},
    'das Thema': {'meanings': ['topic', 'subject', 'theme', 'issue']},
    'das Verfahren': {'meanings': ['procedure', 'process', 'method', 'technique']},
    'akzeptieren': {'meanings': ['accept', 'approve', 'agree', 'admit']},
    'analysieren': {'meanings': ['analyze', 'examine', 'evaluate', 'assess']},
    'ankündigen': {'meanings': ['announce', 'declare', 'notify', 'proclaim']},
    'anwenden': {'meanings': ['apply', 'use', 'employ', 'utilize']},
    'aufhören': {'meanings': ['stop', 'quit', 'cease', 'end']},
    'ausfüllen': {'meanings': ['fill out', 'complete', 'fill in', 'enter']},
    'auslösen': {'meanings': ['trigger', 'cause', 'set off', 'initiate']},
    'beeinträchtigen': {'meanings': ['impair', 'affect', 'hinder', 'damage']},
    'beobachten': {'meanings': ['observe', 'watch', 'monitor', 'notice']},
    'berechtigen': {'meanings': ['authorize', 'entitle', 'permit', 'qualify']},
    'beschleunigen': {'meanings': ['accelerate', 'speed up', 'increase', 'boost']},
    'bestellen': {'meanings': ['order', 'book', 'request', 'reserve']},
    'beweisen': {'meanings': ['prove', 'demonstrate', 'verify', 'confirm']},
    'einhalten': {'meanings': ['comply with', 'keep', 'observe', 'meet']},
    'einsparen': {'meanings': ['save', 'reduce', 'cut back', 'economize']},
    'empfehlen': {'meanings': ['recommend', 'suggest', 'advise', 'propose']},
    'entscheiden': {'meanings': ['decide', 'determine', 'choose', 'resolve']},
    'entsorgen': {'meanings': ['dispose of', 'discard', 'throw away', 'recycle']},
    'erforschen': {'meanings': ['research', 'explore', 'investigate', 'study']},
    'erkennen': {'meanings': ['recognize', 'identify', 'realize', 'detect']},
    'erleichtern': {'meanings': ['ease', 'facilitate', 'simplify', 'help']},
    'erwähnen': {'meanings': ['mention', 'refer to', 'state', 'note']},
    'fördern': {'meanings': ['promote', 'encourage', 'support', 'advance']},
    'funktionieren': {'meanings': ['function', 'work', 'operate', 'run']},
    'gewährleisten': {'meanings': ['ensure', 'guarantee', 'secure', 'provide']},
    'importieren': {'meanings': ['import', 'bring in', 'introduce', 'purchase']},
    'installieren': {'meanings': ['install', 'set up', 'fit', 'configure']},
    'koordinieren': {'meanings': ['coordinate', 'organize', 'arrange', 'manage']},
    'qualifizieren': {'meanings': ['qualify', 'train', 'certify', 'prepare']},
    'reparieren': {'meanings': ['repair', 'fix', 'restore', 'mend']},
    'reservieren': {'meanings': ['reserve', 'book', 'hold', 'arrange']},
    'spezialisieren': {'meanings': ['specialize', 'focus', 'concentrate', 'train']},
    'stärken': {'meanings': ['strengthen', 'reinforce', 'improve', 'support']},
    'teilen': {'meanings': ['share', 'divide', 'split', 'distribute']},
    'übertragen': {'meanings': ['transfer', 'transmit', 'assign', 'convey']},
    'vereinfachen': {'meanings': ['simplify', 'ease', 'streamline', 'reduce']},
    'vermehren': {'meanings': ['increase', 'multiply', 'expand', 'grow']},
    'verpacken': {'meanings': ['pack', 'package', 'wrap', 'bundle']},
    'verschaffen': {'meanings': ['obtain', 'provide', 'secure', 'procure']},
    'vortragen': {'meanings': ['present', 'deliver', 'lecture', 'report']},
    'wahrnehmen': {'meanings': ['perceive', 'notice', 'attend', 'recognize']},
    'wechseln': {'meanings': ['change', 'switch', 'exchange', 'replace']},
    'weiterentwickeln': {'meanings': ['develop further', 'improve', 'advance', 'enhance']},
    'zeichnen': {'meanings': ['draw', 'sign', 'mark', 'illustrate']},
}
